"""empty message

Revision ID: 4625c5e3ba33
Revises: 1aeaa6e02fac
Create Date: 2020-05-12 18:23:22.861656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4625c5e3ba33'
down_revision = '1aeaa6e02fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=240), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
