"""empty message

Revision ID: 798994b66f69
Revises: fd9c83b4a7db
Create Date: 2020-05-13 15:33:32.156174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798994b66f69'
down_revision = 'fd9c83b4a7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.alter_column('venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('shows', 'start_time')
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
